language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)
